### ISSUE TITLE
BioGenerics compat line prevents Pkg from adding

### ISSUE THREAD

**Issue by mmattocks** [BioJulia/FASTX.jl#3]
The compat line for the BioGenerics dependency requires 1.0, while BioGenerics is on 0.1. The package can't be added from it's repository as is, I don't think.

**Comment by BenJWard** [comment]
Thanks for highlighting this @mmattocks, this is probably an error or typo on our part, since FASTX has not been officially released yet, we can simply change this in FASTX.jl's Project file.

**Comment by BenJWard** [comment]
This has been fixed and a v1.0 release of FASTX has been made to the [BioJuliaRegistry](https://github.com/BioJulia/BioJuliaRegistry)

**Comment by mmattocks** [comment]
Hi Ben! Thanks for the response. I have been using the BioSequences.FASTA namespace for the last little while, will this eventually be migrated to FASTX.jl?

**Comment by BenJWard** [comment]
Yeah FASTX is basically BioSequences.FASTA and BioSequences.FASTQ.
Except it uses TranscodingStreams instead of BufferedStreams, and uses a newer submodule of Automa. So same functionality, different updated internals.

BioSequences is being changed in a version 2 I'm working on, with an updated type hierarchy and sequence types, and one of the changes is to move IO out to it's own packages, to reduce the code in BioSequences and let users just install the modules they need for the formats they work with.

This change was decided since it's difficult to bikeshed some file formats into BioSequences, BioAlignments, GenomicFeatures and so on: BAM and SAM store alignments, but people do also sometimes use them in scripts as a source of reads, and phylogenetics file formats store trees, sequences and alignments, and other info like scoring matrices sometimes.

**Comment by mmattocks** [comment]
Sounds good to me, thanks for all your guys' work on this stuff!
